<?php

return array(
    'notebook' => 'book',
    'lock' => 'lock',
    'lock-unlocked' => 'unlock',
    'broom' => 'broom',
    'star' => 'star',
    'livejournal' => 'newspaper',
    'contact' => 'address-card',
    'lightning' => 'bolt',
    'light-bulb' => 'lightbulb',
    'pictures' => 'images',
    'reports' => 'chart-line',
    'books' => 'swatchbook',
    'marker' => 'marker',
    'lens' => 'camera',
    'alarm-clock' => 'bell',
    'animal-monkey' => 'cat',
    'anchor' => 'anchor',
    'bean' => 'coffee',
    'car' => 'car',
    'disk' => 'save',
    'cookie' => 'cookie',
    'burn' => 'radiation',
    'clapperboard' => 'film',
    'bug' => 'bug',
    'clock' => 'clock',
    'cup' => 'mug-hot',
    'home' => 'home',
    'fruit' => 'apple-alt',
    'luggage' => 'suitcase',
    'guitar' => 'guitar',
    'smiley' => 'smile',
    'sport-soccer' => 'futbol',
    'target' => 'bullseye',
    'medal' => 'medal',
    'phone' => 'phone',
    'store' => 'store',
);
